# Generated by Django 5.2.16 on 2026-07-12 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_set_foundation_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Farm's GPS latitude, captured at signup (browser geolocation or manual entry). Optional: used to personalize weather-based prefill in farm/weather.py — if unset, weather fetching falls back to the global FARM_LATITUDE/FARM_LONGITUDE settings (the foundation farmer's location).", max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Farm's GPS longitude — see latitude's help_text.", max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
