# Generated by Django 5.2.16 on 2026-07-12 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text="Farm address as typed by the farmer at signup, geocoded into latitude/longitude below (see accounts.views.signup and farm.weather.geocode_address). Kept even if geocoding fails so the farmer's input isn't silently lost.", max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Farm's GPS latitude, geocoded from `address` at signup. Optional: used to personalize weather-based prefill in farm/weather.py — if unset, weather fetching falls back to the global FARM_LATITUDE/FARM_LONGITUDE settings (the foundation farmer's location).", max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
