# Generated by Django 5.2.16 on 2026-07-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, help_text="Google's stable per-account ID ('sub' claim), set the first time this user signs in with Google (see accounts/google_oauth.py, accounts/views.py's google_callback). Stable for the life of the Google account even if its email changes later, unlike matching on email alone. null=True (not blank default) so MySQL's unique index only enforces uniqueness among accounts that actually have one linked -- most accounts never will.", max_length=255, null=True, unique=True),
        ),
    ]
