# Generated by Django 5.2.16 on 2026-07-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_google_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_foundation_farmer',
            field=models.BooleanField(default=False, help_text="The one farmer whose historical DailyLog data seeds every new farmer's bootstrap forecasting model (see forecasting/management/commands/train_forecast_model.py). At most one user may ever have this set — enforced in save() below, not a DB constraint. Left over from when MySQL was the target (it doesn't support conditional/partial unique constraints, Django system check W036); Postgres does, so a partial UniqueConstraint here (like unique_generation_per_owner on Flock) is a viable follow-up, not attempted yet."),
        ),
    ]
