# Generated by Django 5.2.16 on 2026-07-24 16:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Optional profile picture, set by the farmer from Account Settings (accounts/views.py's account_settings). Falls back to an initial-letter avatar in the UI (templates/base.html) when unset.", null=True, upload_to='avatars/', validators=[accounts.models.validate_avatar_size]),
        ),
    ]
