# Generated by Django 5.2.16 on 2026-09-24 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional PH mobile number in 11-digit local form (09XXXXXXXXX), normalized by accounts/contact.py\'s normalize_ph_mobile. Login-only: farmers can type it into the login form instead of their name or email (accounts/auth_backends.py). No SMS is ever sent to it. null (not "") when unset so the unique index only covers accounts that actually entered one -- same pattern as google_sub.', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'Enter an 11-digit mobile number (09XXXXXXXXX).')]),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_consented_at',
            field=models.DateTimeField(blank=True, help_text='When the farmer agreed to the Privacy Notice (templates/privacy.html) -- the signup consent checkbox, or creating an account via Google sign-in. Required under the Data Privacy Act of 2012 (RA 10173) since the app collects personal information. Null for accounts created before the notice existed.', null=True),
        ),
    ]
