# Generated by Django 5.2.16 on 2026-07-09 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='egg_count',
            field=models.PositiveIntegerField(help_text="Reasonable range up to 1000/day, padded from the historical dataset's observed 112-487.", validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='feed_intake_kg',
            field=models.DecimalField(decimal_places=2, help_text="Reasonable range 0-150 kg/day, padded from the historical dataset's observed 35.5-100.0.", max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='flock_age_weeks',
            field=models.PositiveIntegerField(help_text="Reasonable range 1-150 weeks, padded from the historical dataset's observed 23-107.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='humidity_pct',
            field=models.DecimalField(decimal_places=1, help_text='0-100%, a hard physical ceiling rather than just a historical range.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='temperature_c',
            field=models.DecimalField(decimal_places=1, help_text="Reasonable range 0-45°C, padded from the historical dataset's observed 24.0-34.4.", max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(45)]),
        ),
    ]
