# Generated by Django 5.2.16 on 2026-07-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_dailylog_egg_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='caging_period',
            field=models.PositiveIntegerField(default=1, help_text='Caging-period marker from the historical CSV (itikcare-spec.md section 10). Used only to segment training data around free-range gaps — never fed to the RF model as a raw feature.'),
            preserve_default=False,
        ),
    ]
