# Generated by Django 5.2.16 on 2026-07-10 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_dailylog_caging_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='flock_size',
            field=models.PositiveIntegerField(help_text='Total duck count that day (includes males).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
