# Generated by Django 5.2.16 on 2026-07-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_dailylog_flock_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='is_caged',
            field=models.BooleanField(default=True, help_text="False while ducks are free-range in the field; daily logging and forecasts pause until it's caged again."),
        ),
    ]
