# Generated by Django 5.2.16 on 2026-07-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_flock_is_caged'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='pending_flock_size',
            field=models.PositiveIntegerField(blank=True, help_text="Duck count confirmed when resuming caging after a free-range period; consumed as the next DailyLog's flock_size prefill, then cleared.", null=True),
        ),
    ]
