# Generated by Django 5.2.16 on 2026-07-19 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_flock_owner_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='pending_feed_intake_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Feed intake confirmed at registration; consumed as the next DailyLog's feed_intake_kg prefill on a flock's very first entry, then cleared.", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='flock',
            name='pending_flock_age_weeks',
            field=models.PositiveIntegerField(blank=True, help_text="Flock age confirmed at registration; consumed as the next DailyLog's flock_age_weeks prefill on a flock's very first entry, then cleared.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
