# Generated by Django 5.2.16 on 2026-07-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_flock_pending_feed_intake_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='is_locked',
            field=models.BooleanField(default=False, help_text="True once this row existed at the time train_forecast_model last successfully persisted a model for its owner. Every retrain is a full refit over the owner's entire DailyLog history (never warm_start — see that command's module docstring), so a persisted model has already learned from whatever values this row held at that time. Locked rows can never be edited or deleted again (farm/views.py::farm_record_edit/farm_record_delete)."),
        ),
    ]
