# Generated by Django 5.2.16 on 2026-09-17 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_dailylog_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(help_text='The date this reminder was for (owner had no DailyLog for it yet).')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_log_reminders', to='farm.flock')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_log_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reminder_date'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'reminder_date'), name='unique_reminder_per_owner_per_day')],
            },
        ),
    ]
