# Generated by Django 5.2.16 on 2026-07-09 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(help_text='The input variable/rule that triggered this recommendation.', max_length=50)),
                ('message', models.TextField(help_text='Plain-language, farmer-facing actionable advice.')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='forecasting.forecast')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
