# Generated by Django 5.2.16 on 2026-07-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium_low', 'Medium-Low'), ('medium', 'Medium/Normal'), ('medium_high', 'Medium-High'), ('high', 'High')], default='medium', max_length=11),
        ),
    ]
