# Generated by Django 5.2.16 on 2026-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_recommendation_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='learn_more',
            field=models.TextField(blank=True, default='', help_text="Rationale paragraph from Annex A's 'Learn More' column."),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reading_summary',
            field=models.CharField(blank=True, default='', help_text="The raw farm reading that triggered this rule, e.g. '33.0°C'.", max_length=100),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='status',
            field=models.CharField(blank=True, default='', help_text="Short status label shown before the message, e.g. 'Underfed', 'High'.", max_length=30),
        ),
    ]
