# Generated by Django 5.2.16 on 2026-07-09 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(help_text='The date this forecast is predicting for.')),
                ('predicted_daily_yield', models.DecimalField(decimal_places=2, max_digits=8)),
                ('predicted_tri_day_yield', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feature_importances', models.JSONField(help_text='RF feature importance scores at prediction time, e.g. {"temperature_c": 0.31, "feed_intake_kg": 0.22, ...}. Feeds the prescriptive module\'s rule prioritization.')),
                ('model_version', models.CharField(help_text='Identifies which trained model artifact produced this forecast.', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='farm.flock')),
                ('source_logs', models.ManyToManyField(related_name='forecasts', to='farm.dailylog')),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
    ]
