# Generated by Django 5.2.16 on 2026-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_dailylog_caging_period'),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(fields=('flock', 'forecast_date'), name='unique_forecast_per_flock_date'),
        ),
    ]
