# Generated by Django 5.2.16 on 2026-07-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_forecast_unique_forecast_per_flock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='predicted_next_day1_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Best-effort forecast for forecast_date + 1 day (tomorrow). Derived by recursively re-applying the same daily_pipeline used for predicted_daily_yield, not a separately trained model — see forecasting/services.py's _predict_next_days. Null until a forecast generated after this field existed.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='predicted_next_day2_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Best-effort forecast for forecast_date + 2 days. See predicted_next_day1_yield — this step's lag1/roll3 inputs partly depend on that day's own prediction, so error compounds further here.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='predicted_next_day3_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Best-effort forecast for forecast_date + 3 days. See predicted_next_day1_yield — the most compounded of the three recursive steps.', max_digits=8, null=True),
        ),
    ]
